name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev build-essential git libssl-dev libffi-dev openjdk-17-jdk unzip wget

    - name: Install Python dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install cython==0.29.36 buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
